# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Every 15 mins from 0600 - 2300
  schedule:
    - cron: "*/15 6-23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install stuff
        run: sudo apt install gnuplot

      - name: Do stuff
        run: |
          cd $GITHUB_WORKSPACE
          ./collect.sh
          gnuplot -e "gymname='gym1.data'; outputname='gym1.png'" gym.p
          gnuplot -e "gymname='gym2.data'; outputname='gym2.png'" gym.p
          gnuplot -e "gymname='gym3.data'; outputname='gym3.png'" gym.p
          gnuplot -e "gymname='gym4.data'; outputname='gym4.png'" gym.p

      - name: Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "data scrape commit"
          git push origin master
